version: "3.8"
services:
  app:
    env_file: ../${APP}/.env
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    container_name: "${APP}_app"
    volumes:
      - ../${APP}:/usr/local/src
    environment:
      - APP_URL=${APP_URL}
      - APP_DIR=../${APP}
      - APP_NAME=${APP}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_TESTING_HOST=${DB_TESTING_HOST}
      - DB_TESTING_DATABASE=${DB_TESTING_DATABASE}
      - DB_TESTING_USERNAME=${DB_TESTING_USERNAME}
      - DB_TESTING_PASSWORD=${DB_TESTING_PASSWORD}
  web:
    image: nginx:1.18-alpine
    ports:
      - "${APP_PORT}:${APP_PORT}"
    container_name: "${APP}_web"
    volumes:
      - ../${APP}:/usr/local/src
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./infra/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./infra/nginx/certs:/etc/nginx/certs
      - ./infra/nginx/private:/etc/nginx/private
    working_dir: /usr/local/src
    environment:
      - WEB_DOMAIN=${WEB_DOMAIN}
      - APP_PORT=${APP_PORT}
      - SSL=${SSL}
      - SSL_PASSWD=${SSL_PASSWD}
    command: /bin/ash -c "envsubst '$$WEB_DOMAIN$$APP_PORT$$SSL' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && envsubst '$$SSL_PASSWD' < /etc/nginx/private/pass_file.txt.template > /etc/nginx/private/pass_file.txt && nginx -g 'daemon off;'"
  db:
    build: ./infra/mysql
    container_name: "${APP}_db"
    volumes:
      - db-store:/var/lib/mysql
      - ./infra/mysql/initdb:/docker-entrypoint-initdb.d
      - ./infra/mysql/logs:/var/log/mysql
    ports:
      - 33060:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  db-testing:
    build: ./infra/mysql
    container_name: "${APP}_db-testing"
    volumes:
      - db-testing-store:/var/lib/mysql
      - ./infra/mysql/logs:/var/log/mysql
    environment:
      - MYSQL_DATABASE=${DB_TESTING_DATABASE}
      - MYSQL_USER=${DB_TESTING_USERNAME}
      - MYSQL_PASSWORD=${DB_TESTING_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_TESTING_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${DB_TESTING_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=$DB_TESTING_PASSWORD}
      - TZ=${TZ}
    ports:
      - ${DB_TESTING_PORT}:3306
volumes:
  db-store:
    name: ${APP}_db-store
  db-testing-store:
    name: ${APP}_db-testing-store
